---
#- name: run aws configure
#  expect:
#   command: "aws configure"
#   responses:
#    'AWS Access Key ID': 
#    'AWS Secret Access Key':
#    'Default region name':
#    'Default output format':
#   no_log: true

- name: copy deploymen directry
  template:
    src: "{{item}}"
    dest: "{{ansible_env.HOME}}/{{item}}"
  with_items:
   - deployment.yaml
  
#- name: create a deployment
#  k8s:
#   state: present
#   src: {{ansible_env.HOME}}/deployment.yaml 