---
- name: run aws configure
  expect:
   command: "aws configure"
   responses:
    'AWS Access Key ID': "{{lookup('vars','env') + '_' + lookup('vars','access_key')}}"
    'AWS Secret Access Key': "{{lookup('vars','env') + '_' + lookup('vars','secret_key')}}"
    'Default region name': us-east-1
    'Default output format': json
   no_log: true

- name: copy deploymen & service to {{ansible_env.HOME}}
  template:
    src: "{{item}}"
    dest: "{{ansible_env.HOME}}/{{item}}"
  with_items:
   - deployment.yaml
   - service.yaml
  
- name: create a deployment
  k8s:
   state: present
   src: "{{ansible_env.HOME}}/deployment.yaml"

- name: create a service
  k8s:
   state: present
   src: "{{ansible_env.HOME}}/service.yaml"
